import type { NanosiemClient } from '@nano-rs/investigator-core';
import { type ToolResult, ok, err } from './utils.js';

// ---------------------------------------------------------------------------
// Tool definitions
// ---------------------------------------------------------------------------

export const TOOLS = [
  {
    name: 'list_alerts',
    annotations: { readOnlyHint: true },
    description:
      'List alerts from the SIEM with optional filters. Returns alert summaries including severity, status, rule name, and timestamps. Use this to review the current alert queue or find alerts matching specific criteria.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        status: {
          type: 'string',
          enum: ['new', 'acknowledged', 'closed'],
          description: 'Filter by alert status.',
        },
        severity: {
          type: 'string',
          enum: ['critical', 'high', 'medium', 'low', 'informational'],
          description: 'Filter by alert severity level.',
        },
        rule_id: {
          type: 'string',
          description: 'Filter alerts generated by a specific detection rule ID.',
        },
        assigned_to: {
          type: 'string',
          description: 'Filter alerts assigned to a specific analyst user ID.',
        },
        limit: {
          type: 'number',
          description: 'Maximum number of alerts to return (default 50).',
        },
        offset: {
          type: 'number',
          description: 'Number of alerts to skip for pagination.',
        },
      },
    },
  },
  {
    name: 'get_alert',
    annotations: { readOnlyHint: true },
    description:
      'Get full details for a single alert, including matched events, associated detection rule information, and AI triage hints. Use this to deeply inspect an alert during investigation.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        id: {
          type: 'string',
          description: 'The unique alert ID to retrieve.',
        },
      },
      required: ['id'],
    },
  },
  {
    name: 'get_alert_counts',
    annotations: { readOnlyHint: true },
    description:
      'Get a summary breakdown of alert counts by severity and status. Useful for understanding the current alert landscape and prioritizing triage work.',
    inputSchema: {
      type: 'object' as const,
      properties: {},
    },
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function text(value: string): ToolResult {
  return { content: [{ type: 'text', text: value }] };
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

export async function handleAlertsTool(
  name: string,
  args: Record<string, unknown>,
  client: NanosiemClient
): Promise<ToolResult> {
  switch (name) {
    // ------------------------------------------------------------------
    case 'list_alerts': {
      const params: Record<string, unknown> = {};
      if (args.status !== undefined) params.status = args.status;
      if (args.severity !== undefined) params.severity = args.severity;
      if (args.rule_id !== undefined) params.rule_id = args.rule_id;
      if (args.assigned_to !== undefined) params.assigned_to = args.assigned_to;
      if (args.limit !== undefined) params.limit = args.limit;
      if (args.offset !== undefined) params.offset = args.offset;

      const res = await client.listAlerts(
        params as {
          status?: string;
          severity?: string;
          rule_id?: string;
          assigned_to?: string;
          limit?: number;
          offset?: number;
        }
      );

      if (!res.success) {
        return err(`Failed to list alerts: ${res.error?.message ?? 'Unknown error'}`);
      }

      const alerts = res.data ?? [];
      if (alerts.length === 0) {
        return text('No alerts found matching the specified filters.');
      }

      const summary = alerts.map((a) => {
        const parts = [
          `ID: ${a.id}`,
          `Rule: ${a.rule_name ?? a.rule_id}`,
          `Severity: ${a.severity}`,
          `Status: ${a.status}`,
        ];
        if (a.assigned_to) parts.push(`Assigned: ${a.assigned_to}`);
        if (a.matched_event_count) parts.push(`Events: ${a.matched_event_count}`);
        parts.push(`Created: ${a.created_at}`);
        return parts.join(' | ');
      });

      return text(`Found ${alerts.length} alert(s):\n\n${summary.join('\n')}`);
    }

    // ------------------------------------------------------------------
    case 'get_alert': {
      const id = args.id as string;
      if (!id) return err('Missing required argument: id');

      const res = await client.getAlert(id);
      if (!res.success) {
        return err(`Failed to get alert: ${res.error?.message ?? 'Unknown error'}`);
      }

      return text(JSON.stringify(res.data, null, 2));
    }

    // ------------------------------------------------------------------
    case 'get_alert_counts': {
      const res = await client.getAlertCounts();
      if (!res.success) {
        return err(`Failed to get alert counts: ${res.error?.message ?? 'Unknown error'}`);
      }

      const counts = res.data ?? { total: 0, new: 0, acknowledged: 0, closed: 0, by_severity: {} };
      const lines = [
        `Total: ${counts.total}`,
        `New: ${counts.new}`,
        `Acknowledged: ${counts.acknowledged}`,
        `Closed: ${counts.closed}`,
        '',
        'By severity:',
        ...Object.entries(counts.by_severity).map(
          ([sev, count]) => `  ${sev}: ${count}`
        ),
      ];

      return text(lines.join('\n'));
    }

    // ------------------------------------------------------------------
    default:
      return err(`Unknown alerts tool: ${name}`);
  }
}
